POST  http://localhost/api/auth/inscription HTTP/1.1
content-type: application/json

{
    "email": "jules.jaegle@gmail.com",
    "name": "jules",
    "firstname": "jules",
    "username": "jules",
    "password": "toto"
}
###
POST  http://localhost/api/user/updatePassword HTTP/1.1
content-type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjAyNjkxMTQzLCJleHAiOjE2MDI2OTEyMDN9.F4r-RQiCnVPmAQMqzRTDQh9uy_mw1YTK1FYTS6HjODM
x-refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjAyNjkxODAwLCJleHAiOjE2MDI3NzgyMDB9.s8Ob_8g8Bnvw-ivfIsXQNf7fWDjwfRD3PjYtRtCHEeM

{
    "oldPassword": "Qwerty12;",
    "password": "Qwerty12;"
}
###
POST  http://localhost/api/auth/login HTTP/1.1
content-type: application/json

{
    "username": "jules",
    "password": "Qwerty12;"
}
###
POST  http://localhost/api/auth/resetPassword HTTP/1.1
content-type: application/json

{
    "userId": 201,
    "password": "Qwerty12;"
}
###
POST  http://localhost/api/user/setAvatar/10 HTTP/1.1
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjAyNzc0NTMwLCJleHAiOjE2MDI3NzQ1OTB9.Lme6jRlyiLZr8BJqE0jtbJifghZ6kmJCGawytJXmbBQ
x-refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjAyNzc0NTMwLCJleHAiOjE2MDI4NjA5MzB9.ysBRU0Z8rtxGisgvsZpTIw3aRTVfx3PxF3RKANFzD7s
###
POST  http://localhost/api/auth/forgetPassword HTTP/1.1
content-type: application/json

{
    "email": "jules.jaegle@gmail.com",
    "username": "ok"
}
###
POST  http://localhost/api/user/unlike/Jaleel_Murphy HTTP/1.1
content-type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjA0NDM1ODIwLCJleHAiOjE2MDQ0MzU4ODB9.xj5DCOFUUZoyp9NLZuL7MHzqfUSclina9mg0dg_WWRM
x-refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjA0NDM1ODIwLCJleHAiOjE2MDQ1MjIyMjB9.z0kPR2fFekFOxdojCEb_o-mEhs43kGpDNXtMSMks3fM
###
POST  http://localhost/api/user/like/Jaleel_Murphy HTTP/1.1
content-type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjA0NDM1ODIwLCJleHAiOjE2MDQ0MzU4ODB9.xj5DCOFUUZoyp9NLZuL7MHzqfUSclina9mg0dg_WWRM
x-refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjA0NDM1ODIwLCJleHAiOjE2MDQ1MjIyMjB9.z0kPR2fFekFOxdojCEb_o-mEhs43kGpDNXtMSMks3fM
###
POST  http://localhost/api/user/report/toto HTTP/1.1
content-type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTYwMTk3Nzk3OCwiZXhwIjoxNjAxOTc4MDM4fQ.7NaH-hpQM8s3LFWjiq3CDUikwK60g5X_Gpel7YZKP1o
x-refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjAyNTg3MjIzLCJleHAiOjE2MDI2NzM2MjN9.BeG9CZ-flE-7baR4-RHXRNONS2dDe-EyjiPStcEFi88
###
POST  http://localhost/api/user/block/toto HTTP/1.1
content-type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTYwMTk3Nzk3OCwiZXhwIjoxNjAxOTc4MDM4fQ.7NaH-hpQM8s3LFWjiq3CDUikwK60g5X_Gpel7YZKP1o
x-refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjAyNTg3MjIzLCJleHAiOjE2MDI2NzM2MjN9.BeG9CZ-flE-7baR4-RHXRNONS2dDe-EyjiPStcEFi88
###
POST  http://localhost/api/user/image/41/delete HTTP/1.1
content-type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjAyNzc3NTUyLCJleHAiOjE2MDI3Nzc2MTJ9.ugDPRQ6SgSmtPGIybQ2eb-lu1ls_Y7_b-QjHDxLijqY
x-refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjAyNzc3NTUyLCJleHAiOjE2MDI4NjM5NTJ9.uzsmjs_JrqGbdJNJX59GF0lTUlmFC7QJkIeOm8e-OFk
###
POST http://localhost/api/user/location HTTP/1.1
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjAzMjA0OTk4LCJleHAiOjE2MDMyMDUwNTh9.yTwkat5Ym7CST1vevnDr-SG_ZFfG0N3AdH7tYs_3NXM
x-refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjAzMjA0OTk4LCJleHAiOjE2MDMyOTEzOTh9.eOuRq5iiKgdos7JAo8QyAMA3IJ9GbCjV8TroECtJiF8
content-type: application/json

{
    "lng": 13,
    "lat": 55
}
###

PUT http://localhost/api/user/notifications HTTP/1.1
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjAzOTg4Nzk5LCJleHAiOjE2MDM5ODg4NTl9.hjN75NOMmGnN6OM00qflXriLrcY8NvJN380--MJnLCI
x-refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjAzOTg4Nzk5LCJleHAiOjE2MDQwNzUxOTl9.WBTvYfvi6CxZAKY99TxdwWAGoXrIkG7b8kIpxt9hqGU
###

GET http://localhost/api/chat/users HTTP/1.1
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjAzNzA3NzYzLCJleHAiOjE2MDM3MDc4MjN9.r8J40bjIok91pPrY25CPSehzZsfHKTaudL25ccK4a0o
x-refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjAzNzA3NzYzLCJleHAiOjE2MDM3OTQxNjN9.hOsYmzk9eTGR_GRorBi5KbwlvlDPgdmMhx9KmKBc-a0
###
GET http://localhost/api/chat/messages/Gregory55 HTTP/1.1
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjAzNzA3NzYzLCJleHAiOjE2MDM3MDc4MjN9.r8J40bjIok91pPrY25CPSehzZsfHKTaudL25ccK4a0o
x-refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjAzNzA3NzYzLCJleHAiOjE2MDM3OTQxNjN9.hOsYmzk9eTGR_GRorBi5KbwlvlDPgdmMhx9KmKBc-a0
###
GET http://localhost/api/user/notifications HTTP/1.1
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjAzOTg1ODE0LCJleHAiOjE2MDM5ODU4NzR9.otBCY7uDQDDBI_vpHzGe-8QORdYNfpDZF-zblh7BzQw
x-refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjAzOTg1ODE0LCJleHAiOjE2MDQwNzIyMTR9.3a6qv1HiycfSK6raRXJBJixkY72z7LMcO00zbSGJCLg
###
GET http://localhost/api/user/email HTTP/1.1
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjAzNDQyMTY5LCJleHAiOjE2MDM0NDIyMjl9.0wzsfzNdV2nI9kA8QjalP_a-S9-xiTveZkIzOm8ZFWI
x-refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjAzNDQyMTY5LCJleHAiOjE2MDM1Mjg1Njl9.1_-93BylVKLDt2fI0dqnjaX8XEZjniXhf_-xj2dmRWk
###
GET http://localhost/api/user/location HTTP/1.1
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjAzMTgyNjgyLCJleHAiOjE2MDMxODI3NDJ9.g95oC0ccP16ADu_z9J-iTSqzeBHgLYaIRkOrBqs5rtM
x-refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjAzMTgyNjgyLCJleHAiOjE2MDMyNjkwODJ9.GO95p57Xv8312nC2yBxsCnxd-svkRG1Fe5_V-YKn1yw
###
GET http://localhost/api/auth/canLog HTTP/1.1
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjAzMTAwODU2LCJleHAiOjE2MDMxMDA5MTZ9.T7jV3KIlxsPM5kTELHsXrP70vgRkUK3HHRW5DME2Q5s
x-refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjAzMTAwODU2LCJleHAiOjE2MDMxODcyNTZ9.mXWoslsTVStfwGTPj2XWXcQHRwq-Af9P6evRHAIWYGc
###
GET http://localhost/api/user/images HTTP/1.1
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjAzMjA1MDYyLCJleHAiOjE2MDMyMDUxMjJ9.No_F8Kgyh02FSSdXg2n5w8IOBnSpyFsU_2CptLzd8xM
x-refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjAzMjA0OTk4LCJleHAiOjE2MDMyOTEzOTh9.eOuRq5iiKgdos7JAo8QyAMA3IJ9GbCjV8TroECtJiF8
###
GET http://localhost/api/user/avatar HTTP/1.1
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjAyODUxOTg0LCJleHAiOjE2MDI4NTIwNDR9.sTmleqKdz8gjciqnoSsNCFQ0umwP-bMPQy2qHv7B4gg
x-refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjAyODUxOTg0LCJleHAiOjE2MDI5MzgzODR9.O5yWs61dNoubOOrLdvwTMjlCvocezNoyzL1cG9ZBoSA
###
GET http://localhost/api/user/tags HTTP/1.1
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTYwMTk3Nzk3OCwiZXhwIjoxNjAxOTc4MDM4fQ.7NaH-hpQM8s3LFWjiq3CDUikwK60g5X_Gpel7YZKP1o
x-refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjAyNTg4Nzc4LCJleHAiOjE2MDI2NzUxNzh9.Oiv2RZz3yQijJRqfQ-FnUOyShpqxbFdsWgXe8T5f2UY
###
GET http://localhost/api/user/infos HTTP/1.1
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTYwMTk3Nzk3OCwiZXhwIjoxNjAxOTc4MDM4fQ.7NaH-hpQM8s3LFWjiq3CDUikwK60g5X_Gpel7YZKP1o
x-refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjAyNTg4Nzc4LCJleHAiOjE2MDI2NzUxNzh9.Oiv2RZz3yQijJRqfQ-FnUOyShpqxbFdsWgXe8T5f2UY
###
GET http://localhost/api/matches?perPage=15&ageMax=24&tags[0]=1&tags[1]=&tags[2]=1&tags[3]=&ageMin=5&sortBy=distance&orderBy=ASC HTTP/1.1
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjAzNzI0Nzg2LCJleHAiOjE2MDM3MjQ4NDZ9.pWvYXcSfSAZBVCeXeZqFO3cIWAFhWJPgYsJMbXp4fII
x-refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjAzNzI0Nzg2LCJleHAiOjE2MDM4MTExODZ9.63Mr4IS5sn5TiXcjLJ7XcSwKQ9lLxOKovFjowS56QY8
###
GET http://localhost/api/user/likes HTTP/1.1
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjAzMDk3NzAxLCJleHAiOjE2MDMwOTc3NjF9.Lf7-pUh5KuV3N14cNXQ_tX7JOulkobTGF03fjqTtcHU
x-refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjAzMDk3NzAxLCJleHAiOjE2MDMxODQxMDF9.jPEaGSppqydJdbuwE_vkQLO59BzSMIAMpzAEnRpNytk
###
GET http://localhost/api/user/matches HTTP/1.1
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjAzNzA3NzYzLCJleHAiOjE2MDM3MDc4MjN9.r8J40bjIok91pPrY25CPSehzZsfHKTaudL25ccK4a0o
x-refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjAzNzA3NzYzLCJleHAiOjE2MDM3OTQxNjN9.hOsYmzk9eTGR_GRorBi5KbwlvlDPgdmMhx9KmKBc-a0
###
GET http://localhost/api/user/views HTTP/1.1
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjAzNzA3NzYzLCJleHAiOjE2MDM3MDc4MjN9.r8J40bjIok91pPrY25CPSehzZsfHKTaudL25ccK4a0o
x-refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjAzNzA3NzYzLCJleHAiOjE2MDM3OTQxNjN9.hOsYmzk9eTGR_GRorBi5KbwlvlDPgdmMhx9KmKBc-a0
###
GET http://localhost/api/user/profile/jules HTTP/1.1
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjAzNzkyOTU2LCJleHAiOjE2MDM3OTMwMTZ9.GgSy3GYsjCjRHNpFT-qHT0L7dSbbD5UWwZ1nyhoU36M
x-refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMSwiaWF0IjoxNjAzNzkyOTU2LCJleHAiOjE2MDM4NzkzNTZ9.rFTEzuTSlPEm2ZqQbq7kD1JISpF59N5oMCih_ailh-o
###
GET http://localhost/api/test HTTP/1.


SELECT u.username, u.age, u.sexualOrientation, u.gender, u.popularityScore, u.latitude, u.longitude, u.avatar, s.tags, t.distance, l.likedId
FROM users AS u
##Jointure pour les likes
LEFT JOIN likes as l ON l.likedId = 201 AND l.likeId = u.id
##Jointure pour les distances
INNER JOIN (SELECT a, id, c, 6371 * c as distance, longitude, latitude
            FROM (SELECT a, id, 2 * ATAN(SQRT(a) / SQRT(1 - a)) as c , longitude, latitude
                  FROM (SELECT(POW(SIN((-26.3319 - latitude) / 2),2) + COS(latitude) * 		COS(-26.3319) * POW(SIN((-160.9677 - longitude) / 2),2)) as a, longitude, latitude, id
     FROM users) t1) t2) as t ON u.id = t.id
##jointure pou les tags
INNER JOIN (SELECT userId, GROUP_CONCAT(tagId) as tags 
            FROM user_tag 
            WHERE tagId IN (1,3, 2, 6) GROUP BY userId) as s 
ON u.id = s.userId WHERE u.id <> 1 ORDER BY LENGTH(tags) DESC 
LIMIT 170 OFFSET 0

